name: "⚡ LLM README Tester"
description: "LLM-powered unit tests for your README.md — powered by Gemini AI and pure vibes."

branding:
  icon: book-open
  color: purple

inputs:
  google_api_key:
    description: "Your Google Gemini API key (store it as a secret: GOOGLE_API_KEY)"
    required: true

  checks:
    description: >
      Comma-separated list of checks to run on your README.
      Options: description, install, usage, license, demo.
      Use "all" to run all checks (default).
    required: false
    default: "all"

runs:
  using: "composite"
  steps:
    - name: 🐍 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: ⚡ Install dependencies with uv
      run: uv sync
      shell: bash

    - name: 🧪 Run LLM-powered README tests
      run: pytest test_readme.py
      shell: bash
      env:
        GOOGLE_API_KEY: ${{ inputs.google_api_key }}
        README_TEST_CHECKS: ${{ inputs.checks }}
